<!-- jquery -->
document.write('<script type="text/javascript" src="../../style/common/jquery/jquery.min.js"></script>');
<!-- easyUI -->
document.write('<script type="text/javascript" src="../../style/common/jquery-easyui-1.4.4/jquery.easyui.min.js"></script>');
document.write('<script type="text/javascript" src="../../style/common/jquery-easyui-1.4.4/locale/easyui-lang-zh_CN.js"></script>');
<!-- jquery表单验证控件 -->
document.write('<script type="text/javascript" src="../../style/common/validate/jquery.validate.min.js"></script>');
<!-- jquery表单验证控件 -->
document.write('<script type="text/javascript" src="../../style/common/validate/messages_zh.min.js"></script>');
<!-- jquery滚动条控件 -->
document.write('<script type="text/javascript" src="../../style/common/slimscroll/jquery.slimscroll.min.js"></script>');
<!-- jquery侧边栏控件 -->
document.write('<script type="text/javascript" src="../../style/common/metisMenu/jquery.metisMenu.js"></script>');
<!-- jquery弹窗控件 -->
document.write('<script type="text/javascript" src="../../style/common/layer/layer.min.js"></script>');
<!-- jquery选择框控件 -->
document.write('<script type="text/javascript" src="../../style/common/iCheck/icheck.min.js"></script>');

<!-- bootstrap框架 -->
document.write('<script type="text/javascript" src="../../style/common/bootstrap/js/bootstrap.min.js"></script>');
<!-- bootstrap分页插件 -->
document.write('<script type="text/javascript" src="../../style/common/bootstrap/js/bootstrap-paginator.js"></script>');
<!-- bootstrap分页插件 -->
document.write('<script type="text/javascript" src="../../style/common/bootstrap/js/bootstrap-table.min.js"></script>');
<!-- bootstrap分页插件 -->
document.write('<script type="text/javascript" src="../../style/common/bootstrap/js/bootstrap-table-zh-CN.min.js"></script>');
<!-- bootstrap表单验证插件 -->
document.write('<script type="text/javascript" src="../../style/common/bootstrap/js/bootstrapValidator.min.js"></script>');
<!-- Extjs前端UI库 -->
document.write('<script type="text/javascript" src="../../style/common/Extjs/js/ext-base.js"></script>');
<!-- 弹窗控件 -->
document.write('<script type="text/javascript" src="../../style/common/sweetalert/sweetalert.min.js"></script>');
<!-- 日期控件 -->
document.write('<script type="text/javascript" src="../../style/common/My97DatePicker/WdatePicker.js"></script>');
<!-- Echarts控件 -->
document.write('<script type="text/javascript" src="../../style/common/echarts/echarts.min.js"></script>');
<!-- Json控件 -->
document.write('<script type="text/javascript" src="../../style/common/json/json.js"></script>');
<!-- 表格排序控件 -->
document.write('<script type="text/javascript" src="../../style/common/sortable/sortabletable.js"></script>');

